config/routes.rb
# frozen_string_literal: true
require "sidekiq/web"
# require "sidekiq/cron/web"


Rails.application.routes.draw do
  root 'restaurents#index'


  mount Sidekiq::Web => "/sidekiq"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :user,
      controllers: {
         omniauth_callbacks: 'users/omniauth_callbacks'
      }

  # resources :session, only: [:index]
  # resources :admin

  resource :user, except: :create
  # User routes
  # post '/login', to: 'application#login'

  # post "/signup", to: "users#create"
  # resource :user,  except: :create

  # Restaurent routes
  get '/restaurent/search', to: 'restaurents#search_restaurent'
  resources :restaurents do
    resources :categories, shallow: true do
      resources :dishes, shallow: true
    end
  end

  resources :categories, only: [:create]
  resources :dishes, only: %i[create index]
  # get '/categories/:restaurent_id' to: "categories#create"

  # resources :categories do
  #   resources :dishes , shallow: true
  # end

  # Dish Routes
  # resources :dishes
  # get '/dish/search', to: 'dishes#search_dish'
  # get '/category/search', to: 'dishes#filter_by_category'

  # Cart Routes
  # post '/add_to_cart' , to: "carts#add_item"
  resources :carts
  get '/clearcart', to: 'carts#clear_cart'

  # Orders Routes
  resources :orders
end

app/models/restaurent.rb
# frozen_string_literal: true

class Restaurent < ApplicationRecord
  # belongs_to :owner, foreign_key: 'user_id'

  belongs_to :user
  has_many :categories, dependent: :destroy
  has_many :dishes, through: :categories
  accepts_nested_attributes_for :categories, allow_destroy: true
  before_save :remove_space

  enum status: { 'open' => 'open', 'close' => 'close' }

  validates :name, :place, :status, presence: true
  # validate :owner_only_add_restaurent

  # private
  def remove_space
    self.name = name.strip
    self.place = place.strip
  end

  def owner_only_add_restaurent
    return if user.type == 'Owner'

    errors.add(:base, 'Only Owner have permission to add Restaurents.')
  end
end

app/controllers/restaurents_controller.rb
# frozen_string_literal: true

class RestaurentsController < ApplicationController
  before_action :set_values, only: %i[show update destroy edit]

  def index
    if current_user.owner?
      @restaurents = current_user.restaurents
      flash.now[:notice] = "We have exactly #{@restaurents.size} Restaurent available."
    else
      @restaurents = Restaurent.where(status: 'open')
    end
    @restaurents = @restaurents.paginate(page: params[:page], per_page: 2)
  end

  def new
    @restaurent = current_user.restaurents.new
    @restaurent.categories.new
    @restaurent.categories.each { |category| category.dishes.new }
  end

  def show
    @restaurent = if current_user.owner?
                    current_user.restaurents.includes(categories: :dishes).find(params[:id])
                  else
                    Restaurent.find(params[:id])
                  end
  end

  def create
    @restaurent = current_user.restaurents.new(restaurent_params)
    if @restaurent.save
      redirect_to root_path, status: :created
    else
      render :new
      render json: 'Error While Creating Restaurent', status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @restaurent.update(restaurent_params)
        format.html { redirect_to root_url, notice: 'Restaurent was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurent.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @restaurent.destroy
      redirect_to root_path
    else
      @restaurent
    end
  end

  def search_restaurent
    restaurent = Restaurent.where('name like ?', "%#{params[:name].strip}%")
    return render json: restaurent unless restaurent.empty?

    render json: { error: 'No such restaurent found... ' }, status: 404
  end

  private

  def restaurent_params
    params.require(:restaurent).permit(
      :name,
      :place,
      :status,
      categories_attributes: [
        :id,
        :name,
        { dishes_attributes: %i[
          id
          name
          price
          dish_type
        ] }
      ]
    )
  end

  def set_values
    @restaurent = Restaurent.find(params[:id])
  end
end

app/views/restaurents/_form.html.erb
<%= form_with(model: restaurent) do |form| %>
  <% if restaurent.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(restaurent.errors.count, "error") %> prohibited this restaurent from being saved:</h2>

      <ul>
        <% restaurent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :place, style: "display: block" %>
    <%= form.text_field :place %>
  </div>

  <div>
    <label for="dish_type">Status</label>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <%= form.select :status, ['open','close' ] %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurents/_restaurent.html.erb
<div id="<%= dom_id restaurent %>">
  <p>
    <strong>Name:</strong>
    <%= restaurent.name %>
  </p>

  <p>
    <strong>Place:</strong>
    <%= restaurent.place %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= restaurent.status %>
  </p>
</div>

app/views/restaurents/edit.html.erb
<h1>Editing restaurent</h1>

<%= render "form", restaurent: @restaurent %><br>

<div>
  <%= link_to "Show this restaurent", @restaurent %> |
  <%= link_to "Back to restaurents", restaurents_path %>
</div>

app/views/restaurents/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zomato - Restaurent</title>
      <style>
        body {
          font-family: Tahoma, sans-serif;
          background-image: url('boat.jpg.jpg');
          background-repeat: no-repeat;
          background-attachment: fixed;
          background-size: cover;
          margin: 0;
          padding: 0;
        }
        h1 {
          color: #007BFF;
          text-align: center;
          padding-top: 20px;
        }
        .container {
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
          background-color: rgba(255, 255, 255, 0.9);
          border: 1px solid #ccc;
          box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .restaurent-card {
          display: flex;
          margin-bottom: 20px;
        }
        .restaurent-details {
          flex: 1;
          padding: 20px;
        }
        .restaurent-name {
          font-size: 24px;
          color: #333;
          margin-bottom: 10px;
        }
        .release-date {
          color: #777;
        }
        .image {
          width: 200px;
          height: 300px;
          margin-right: 20px;
          border: 1px solid #ddd;
          box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
        }
        .actions {
          margin-top: 10px;
        }
        .actions a {
          text-decoration: none;
          color: #007BFF;
          margin-right: 10px;
        }
      </style>
  </head>

  <body>
    <h1>All Restaurent</h1>
    <div class="container">
      <% @restaurents.each do |restaurent| %>
        <div class="restaurent-card">
          <div class="restaurent-details">
            <div class="restaurent-name"><%= restaurent.name %></div>
            <div class="restaurent-place"><%= restaurent.place %></div>
            <div class="restaurent-status"><%= restaurent.status %></div>
            <div class="actions">
              <%= link_to 'Show', restaurent %> 
            </div>
          </div>
        </div>
      <%end%>
    </div>

    <center>
      <%= will_paginate @restaurents,:container => false%></br></br>
    </center> 

    <div>
      <%if current_user.type == 'Owner'%>
        <%= link_to "New restaurent", new_restaurent_path %>
      <%else%>
        <%= link_to "Show Cart", carts_path %>&nbsp&nbsp&nbsp
        <%= link_to "Order History", orders_path %>
      <% end%>
    </div>

  </body>
</html>

app/views/restaurents/new.html.erb
<h1>New restaurent</h1>

<%= render "form", restaurent: @restaurent %><br>

<div>
  <%= link_to "Back to restaurents", restaurents_path %>
</div>

app/views/restaurents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @restaurent %>

<div>
  <%= link_to "Back to restaurents", restaurents_path %> |
  <%= link_to "Show Dish Category", restaurent_categories_path(@restaurent) %> |

  <%if current_user.type == 'Owner'%>
  <%= link_to "Edit this restaurent", edit_restaurent_path(@restaurent) %> |
  <%= button_to "Destroy this restaurent", @restaurent, method: :delete %>
  <%end%>
</div>