config/routes.rb
# frozen_string_literal: true
require "sidekiq/web"
# require "sidekiq/cron/web"


Rails.application.routes.draw do
  root 'restaurents#index'


  mount Sidekiq::Web => "/sidekiq"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :user,
      controllers: {
         omniauth_callbacks: 'users/omniauth_callbacks'
      }

  # resources :session, only: [:index]
  # resources :admin

  resource :user, except: :create
  # User routes
  # post '/login', to: 'application#login'

  # post "/signup", to: "users#create"
  # resource :user,  except: :create

  # Restaurent routes
  get '/restaurent/search', to: 'restaurents#search_restaurent'
  resources :restaurents do
    resources :categories, shallow: true do
      resources :dishes, shallow: true
    end
  end

  resources :categories, only: [:create]
  resources :dishes, only: %i[create index]
  # get '/categories/:restaurent_id' to: "categories#create"

  # resources :categories do
  #   resources :dishes , shallow: true
  # end

  # Dish Routes
  # resources :dishes
  # get '/dish/search', to: 'dishes#search_dish'
  # get '/category/search', to: 'dishes#filter_by_category'

  # Cart Routes
  # post '/add_to_cart' , to: "carts#add_item"
  resources :carts
  get '/clearcart', to: 'carts#clear_cart'

  # Orders Routes
  resources :orders
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  # belongs_to :customer,  foreign_key: 'user_id'

  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :dishes, through: :cart_items

  validate :customer_only_add_restaurent

  def check_unique_restaurent?(restaurent)
    r_id = restaurent.category.restaurent_id
    cart_items.each do |cart_item|
      return true if cart_item.dish.category.restaurent_id != r_id
    end
    false
  end

  private

  def customer_only_add_restaurent
    return if user.type == 'Customer'

    errors.add(:base, 'Only Customer have permission to add Dishes.')
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :set_cart, only: [:index]
  before_action :set_cart_item, only: %i[edit update destroy]

  # before_action :find_id ,only: %i[create]

  def index
    byebug
    @carts = current_user.cart.cart_items
  end

  def show
    @cart_data = current_user.cart.cart_items.includes(:dish)
    @cart_items_data = @cart_data.map do |cart_item|
      {
        id: cart_item.id,
        dish: cart_item.dish.name,
        price: cart_item.dish.price,
        quantity: cart_item.quantity
      }
    end
    # render json: cart_items_data
  end

  def new
    id = params[:format].to_i
    @dish = Dish.find(id)
  end

  def create
    byebug
    dish = Dish.find(params[:dish_id])

    if current_user.cart.check_unique_restaurent?(dish)
      current_user.cart.cart_items.destroy_all
      add_cart = current_user.cart.cart_items.new(cart_item_params)
      notice_message = 'Cart items updated with a new restaurant.'
    else
      add_cart = current_user.cart.cart_items.new(cart_item_params)
      notice_message = 'Dish added to cart successfully.'
    end

    return unless add_cart.save

    redirect_to carts_path, notice: notice_message
  end

  # def create
  #   add_cart = current_user.cart.cart_items.new(cart_item_params)
  #   if add_cart.save
  #     flash[:notice] = "Item Added to your Cart."
  #     redirect_to carts_path
  #   end
  # end

  def edit; end

  def update
    @cart_item = current_user.cart.cart_items.find(params[:cart_item_id])
    if @cart_item.update(cart_item_params)
      render json: 'Item Updated Successfully', status: 200
    else
      render json: @cart_item.errors, status: :unprocessable_entity
    end
  end

  def destroy
    return unless @cart_item.destroy

    redirect_to carts_path
  end

  def clear_cart
    current_user.cart.cart_items.destroy_all
    redirect_to root_path
  end

  private

  def set_cart
    @cart = current_user.create_cart unless current_user.cart.present?
  end

  def set_cart_item
    byebug
    @cart_item = current_user.cart.cart_items.find(params[:id])
  end

  def cart_item_params
    params.permit(:dish_id, :quantity)
  end
end

# def create
#   dish=Dish.find(params[:dish_id])
#   if current_user.cart.check_unique_restaurent?(dish)
#     clear_cart
#     add_cart = current_user.cart.cart_items.new(cart_item_params)
#     notice_message = 'Cart items updated with a new restaurant.'
#   else
#     add_cart=current_user.cart.cart_items.new(cart_item_params)
#     notice_message = 'Dish added to cart successfully.'
#   end
#   if add_cart.save
#     redirect_to carts_path , notice: notice_message
#   end
# end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart&.errors&.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
  <h1>Cart Items</h1>

  <div id="Your Cart">
    <% @carts.each do |cart| %>
      <%= render cart.dish %>
        <div class="restaurent-status">Quantity <%= cart.quantity %></div>
        <%= button_to "remove item", cart_path(cart), method: :delete %>
    </br>
    <% end %>
  </div>

  <%if @carts.any?%>
    <%= link_to "Clear Cart", clearcart_path %>&nbsp&nbsp&nbsp&nbsp&nbsp
    <%= link_to "Order Now", new_order_path %>&nbsp&nbsp&nbsp&nbsp&nbsp
  <%end%>

app/views/carts/new.html.erb
  <body>

  <div class="container">
      <h1>Add Quantity</h1>
        <%= form_with url: "/carts", method: :post do |form| %>
          <label for="quantity">Quantity</label>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp     </br>
          <%= form.select :quantity, [1,2,3,4,5] %>
          <%= form.hidden_field :dish_id, value: @dish.id %></br></br>
        <%= form.submit "Add" %><br>
      <% end %>
  </div>

  <div>
    <%= button_to 'My Cart', carts_path, :method => :get %>
  </div>

  </body>

app/views/carts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cart %>

<div>
  <%= link_to "Edit this cart", edit_cart_path(@cart) %> |
  <%= link_to "Back to carts", carts_path %>

  <%= button_to "Destroy this cart", @cart, method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are You sure"} %>
</div>