config/routes.rb
# frozen_string_literal: true
require "sidekiq/web"
# require "sidekiq/cron/web"


Rails.application.routes.draw do
  root 'restaurents#index'


  mount Sidekiq::Web => "/sidekiq"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :user,
      controllers: {
         omniauth_callbacks: 'users/omniauth_callbacks'
      }

  # resources :session, only: [:index]
  # resources :admin

  resource :user, except: :create
  # User routes
  # post '/login', to: 'application#login'

  # post "/signup", to: "users#create"
  # resource :user,  except: :create

  # Restaurent routes
  get '/restaurent/search', to: 'restaurents#search_restaurent'
  resources :restaurents do
    resources :categories, shallow: true do
      resources :dishes, shallow: true
    end
  end

  resources :categories, only: [:create]
  resources :dishes, only: %i[create index]
  # get '/categories/:restaurent_id' to: "categories#create"

  # resources :categories do
  #   resources :dishes , shallow: true
  # end

  # Dish Routes
  # resources :dishes
  # get '/dish/search', to: 'dishes#search_dish'
  # get '/category/search', to: 'dishes#filter_by_category'

  # Cart Routes
  # post '/add_to_cart' , to: "carts#add_item"
  resources :carts
  get '/clearcart', to: 'carts#clear_cart'

  # Orders Routes
  resources :orders
end

app/models/dish.rb
# frozen_string_literal: true

class Dish < ApplicationRecord
  belongs_to :category

  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy

  # has_many_attached :images , dependent: :destroy
  has_one_attached :image, dependent: :destroy

  enum dish_type: { 'veg' => 'veg', 'nonveg' => 'nonveg' }

  validates :name, :dish_type, :price, presence: true

  validates :price, numericality: { grater_than_or_equal_to: 1 }

  before_save :remove_space

  def image_url
    Rails.application.routes.url_helpers.rails_blob_url(image, only_path: true)
  end

  private

  def remove_space
    self.name = name.strip
  end
end

app/controllers/dishes_controller.rb
# frozen_string_literal: true

class DishesController < ApplicationController
  def index
    @dishes = if params[:name].present? && params[:restaurent_id].present?
                filter_by_category
              elsif params[:name].present?
                search_by_name
              elsif params[:restaurent_id].present?
                search_by_restaurent_id
              elsif params[:category_id].present?
                Category.find(params[:category_id]).dishes
              elsif current_user.customer?
                Dish.all
              else
                current_user.dishes
              end
    @dishes = @dishes.paginate(page: params[:page], per_page: 2)
    # render json: @dish.paginate(page: params[:page], per_page: 2)
  end

  def new
    # @category = Category.new
    # @restaurent = Restaurent.find(params[:restaurent_id])
    @dish = Dish.new
    @category = Category.find(params[:category_id])
  end

  def show
    @dish = Dish.find(params[:id])
  end

  def edit; end

  def create
    # @category = Restaurent.find(params[:restaurent_id]).categories.new(category_params)
    @dish = Category.find(params[:category_id]).dishes.new(dish_params)
    return unless @dish.save

    redirect_to category_dishes_path(@dish.category_id)
  end

  def update
    @dish.update(dish_params)
    # @dish = current_user.dishes.find(params[:dish_id]).update(dish_params)
    # render json: "Dish Updated Successfully", status:200
  end

  def destroy
    if @dish.destroy
      redirect_to category_dishes_path(@dish.category_id)
    else
      format.html { render :new, status: :unprocessable_entity }
    end
  end

  private

  def search_by_restaurent_id
    restaurent_id = params[:restaurent_id]
    return render json: 'Empty Restaurent ID' unless restaurent_id.present?

    Restaurent.find(restaurent_id).dishes
  end

  def filter_by_category
    if current_user.owner?
      owner_dish = current_user.categories.where('categories.name ILIKE ?', "%#{params[:name].strip}%")
      return owner_dish
    end
    Category.where('name ILIKE ?', "%#{params[:name].strip}%")
    customer_dish
  end

  def owner_dish
    current_user.dishes.where('dishes.name ILIKE ?', "%#{params[:name].strip}%")
  end

  def customer_dish
    Dish.where('dishes.name ILIKE ?', "%#{params[:name].strip}%")
  end

  def dish_params
    params.permit(:name, :price, :dish_type, :image)
  end

  # def set_value
  #   @dish = Dish.find(params[:id])
  # end

  def set_value
    @dish = if current_user.owner?
              current_user.dishes.find(params[:id])
            else
              Dish.find(params[:id])
            end
  end
end

app/views/dishes/_dish.html.erb
<html>

<style>
.image {
      width: 200px;
      height: 300px;
      margin-right: 20px;
      border: 1px solid #ddd;
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
    }

</style>

<body>


    <div id="<%= dom_id dish %>">
      <p>
        <strong>Name:</strong>
        <%= dish.name %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= dish.price %>
      </p>

      <p>
        <strong>Dish type:</strong>
        <%= dish.dish_type %>
      </p>

      <p>
        <strong></strong>
        <img src="<%= dish.image.attached? ? dish.image.url : 'no_image_available.jpg' %>" alt="<%= dish.name %>" class="image"> 
      </p>


    </div>
</body>

</html>

app/views/dishes/_form.html.erb
<%= form_with(model: @dish) do |form| %>

  <%unless @dish.nil?%>
  <% if @dish.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this @dish from being saved:</h2>
      <ul>
        <% @dish.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%end%>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :dish_type, style: "display: block" %>
    <%= form.text_field :dish_type %>
  </div>

   <div>
  <label for="image">Image</label>
    <%= form.file_field :image, id: "image" %><br><br>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<div class="container">
	<h1>Dishes</h1>
	<%= form_with model: @dish, method: :post do |form| %>
			<label for="name">Name</label>
			<%= form.text_field :name ,id: "name"%><br><br>

			<label for="price">Price</label>
			<%= form.text_field :price, id: "price" %><br><br>

			<label for="dish_type">Dish_type</label>
			<%= form.text_field :dish_type, id: "dish_type" %><br><br>

			<label for="image">Image</label>
			<%= form.file_field :image, id: "image" %><br><br>
			<%= form.submit "edit dish" %><br>
	<% end %>
</div>

app/views/dishes/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zomato - Dishes</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-image: url('img_girl.jpg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        margin: 0;
        padding: 0;
      }
      h1 {
        color: #007BFF;
        text-align: center;
        padding-top: 20px;
      }
      .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        background-color: rgba(255, 255, 255, 0.9);
        border: 1px solid #ccc;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
      .dish-card {
        display: flex;
        margin-bottom: 20px;
      }
      .dish-details {
        flex: 1;
        padding: 20px;
      }
      .dish-name {
        font-size: 24px;
        color: #333;
        margin-bottom: 10px;
      }
      .release-date {
        color: #777;
      }
      .image {
        width: 200px;
        height: 300px;
        margin-right: 20px;
        border: 1px solid #ddd;
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
      }
      .actions {
        margin-top: 10px;
      }
      .actions a {
        text-decoration: none;
        color: #007BFF;
        margin-right: 10px;
      }
    </style>
  </head>
  <body>
    <h1>All Dishes</h1>
    <div class="container">
      <% @dishes.each do |dish| %>
        <div class="dish-card">
          <img src="<%= dish.image.attached? ? dish.image.url : 'no_image_available.jpg' %>" alt="<%= dish.name %>" class="image">
          <div class="dish-details">
            <div class="dish-name"><%= dish.name %></div>
            <div class="dish-price">₹<%= dish.price %></div>
            <div class="dish_type"><%= dish.dish_type %></div>
            <div class="actions">
            <%if current_user.type=="Owner"%>
              <%= link_to 'Show', dish %>     
            <%else%>
              <%= button_to 'Add to Cart', new_cart_path(dish.id), :method => :get %>
            <%end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

        <center>
          <%= will_paginate @dishes, :container => false%>
        </center>

    <div>
      <%if current_user.type == 'Owner'%>
        <%= link_to "Create New dish", new_category_dish_path %> 
        <%# <%= link_to "Back to Category", restaurent_categories_path() %>  
      <%end%>
    </div>
  </body>
</html>

app/views/dishes/new.html.erb
<body>
  <div class="container">
    <h1>Dishes</h1>
    <%= form_with url: "/dishes", method: :post do |form| %>
      <label for="name">Name</label>
      <%= form.text_field :name ,id: "name"%><br><br>

      <label for="price">Price</label>
      <%= form.text_field :price, id: "price" %><br><br>

      <label for="dish_type">Dish_type</label>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      <%= form.select :dish_type, ['veg','nonveg' ] %>
      </br>

      <label for="image">Image</label>
      <%= form.file_field :image, id: "image" %><br><br>
      <%= form.submit "Create Dish" %><br>
      <%= form.hidden_field :category_id, value: @category.id %>
    <% end %>
    <div class="back-link">
        <%= link_to "Back to Dishes", category_dishes_path %>
    </div>
  </div>
</body>

app/views/dishes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dish %>

<div>
  <%= link_to "Back to dishes", category_dishes_path(category_id: @dish.category_id) %> 
    <%if current_user.type == 'Owner'%> &nbsp &nbsp &nbsp 
      <%= link_to "Edit this dish", edit_dish_path(@dish) %> 
      <%= button_to "Destroy this dish", @dish, method: :delete %>
   <%end%>
</div>