config/routes.rb
# frozen_string_literal: true
require "sidekiq/web"
# require "sidekiq/cron/web"


Rails.application.routes.draw do
  root 'restaurents#index'


  mount Sidekiq::Web => "/sidekiq"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :user,
      controllers: {
         omniauth_callbacks: 'users/omniauth_callbacks'
      }

  # resources :session, only: [:index]
  # resources :admin

  resource :user, except: :create
  # User routes
  # post '/login', to: 'application#login'

  # post "/signup", to: "users#create"
  # resource :user,  except: :create

  # Restaurent routes
  get '/restaurent/search', to: 'restaurents#search_restaurent'
  resources :restaurents do
    resources :categories, shallow: true do
      resources :dishes, shallow: true
    end
  end

  resources :categories, only: [:create]
  resources :dishes, only: %i[create index]
  # get '/categories/:restaurent_id' to: "categories#create"

  # resources :categories do
  #   resources :dishes , shallow: true
  # end

  # Dish Routes
  # resources :dishes
  # get '/dish/search', to: 'dishes#search_dish'
  # get '/category/search', to: 'dishes#filter_by_category'

  # Cart Routes
  # post '/add_to_cart' , to: "carts#add_item"
  resources :carts
  get '/clearcart', to: 'carts#clear_cart'

  # Orders Routes
  resources :orders
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  belongs_to :restaurent
  has_many :dishes, dependent: :destroy
  validates :name, presence: true
  accepts_nested_attributes_for :dishes, allow_destroy: true

  before_save :remove_space

  private

  def remove_space
    self.name = name.strip
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  # before_action :owner_check, except: [:index,:show]
  # before_action :set_category, only: %i[ edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Restaurent.find(params[:restaurent_id]).categories
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
    @restaurent = Restaurent.find(params[:restaurent_id])
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Restaurent.find(params[:restaurent_id]).categories.new(category_params)
    respond_to do |format|
      if @category.save
        # format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.html do
          redirect_to restaurent_categories_url(@category.restaurent_id), notice: 'Category was Successfully Created'
        end
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    redirect_to restaurent_categories_path(@category.restaurent_id) if @category.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = if current_user.owner?
                  current_user.categories.find(params[:id])
                else
                  Category.find(params[:id])
                end
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.call(:category).permit([:name])
  end
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>

  <%unless category.nil?%>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this categoryfrom being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%end%>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %><br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", restaurent_categories_path(restaurent_id: @category.restaurent_id) %>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <div class="category-name"><%= category.name %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp  <%= link_to "Show this category", category %></div></br>
  <% end %>

  <%if current_user.type == 'Owner'%>
    <%= link_to "New category", new_restaurent_category_path %>
  <%end%>
</div>

app/views/categories/new.html.erb
<body>
  <div class="container">
    <h1>Category</h1>
    <%= form_with url: "/categories", method: :post do |form| %>
      <label for="name">Name</label>
      <%= form.text_field :name ,id: "name"%><br><br>
      <%= form.hidden_field :restaurent_id, value: @restaurent.id %>
      <%= form.submit  "Create Category" %><br>
    <% end %>
    
    <div class="back-link">
      <%= link_to "Back to categories", restaurent_categories_path %> 
    </div>
  </div>
</body>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>
<p>
<%= render @category %>
<%= link_to "Dishes", category_dishes_path(category_id: @category.id)%> </br>
</p>

<div>
  <%if current_user.type =='Owner'%>
    <%= link_to "Edit this category", edit_category_path(@category) %> |
    <%= button_to "Destroy this category", @category, method: :delete %>
  <%end%>
  <%# <%= link_to "Back to categories", restaurent_categories_path %> 
</div>